config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "schedule#index"

  resources :check_ins, only: [:update]

  post 'inbound_sms', to: 'inbound_sms#create'

  resources :prescriptions, only: [:index, :new, :create] do
    resources :prescription_schedules, only: [:create]

    get 'check_schedule', to: "prescriptions#check_schedule"
  end


  # For being able to see sidekiq processes if you are an admin
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :trigger_resolutions
  has_many :trigger_resolution_episodes, through: :trigger_resolutions

  validates :name, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  after_create :set_sms_time

  belongs_to :prescription_schedule
  has_one :prescription, through: :prescription_schedule
  validates :scheduled_date, presence: true
  validates :scheduled_time, presence: true

  has_one :text_message

  private

  def set_sms_time
    SendSmsJob.set(wait_until: ("#{self.scheduled_date} #{self.scheduled_time}").to_datetime).perform_later(self.id)
  end
end

app/models/episode_symptom.rb
class EpisodeSymptom < ApplicationRecord
  belongs_to :symptom
  belongs_to :health_episode
end

app/models/health_episode.rb
class HealthEpisode < ApplicationRecord
  has_many :trigger_resolution_episodes
  has_many :episode_symptoms
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  after_create :set_defaults
  belongs_to :user
  belongs_to :product
  has_many :prescription_schedules
  has_many :check_ins, through: :prescription_schedules
  validates :product, presence: true
  validates :amount, presence:true
  validates :instructions, presence: true
  validates :end_date, presence: true
  validates :start_date, presence: true


  private

  def set_defaults
    self.update(active: true)
  end
end

app/models/prescription_schedule.rb
class PrescriptionSchedule < ApplicationRecord
  after_initialize :set_defaults
  belongs_to :prescription
  has_many :check_ins

  validates :prescription, presence: true
  validates :day_of_week, presence: true
  validates :time_of_day, presence: true

  def set_defaults
    self.update(as_needed: false) unless self.as_needed
    self.update(day_of_week: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday") unless self.day_of_week
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prescriptions
  has_many :trigger_resolutions
  has_many :trigger_resolution_episodes, through: :trigger_resolutions
end

app/models/sms.rb
class Sms < ApplicationRecord
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :episode_symptoms
  has_many :health_episodes, through: :episode_symptoms

  validates :name, uniqueness: true, presence: true
end

app/models/text_message.rb
class TextMessage < ApplicationRecord
  belongs_to :check_in

end

app/models/trigger_resolution.rb
class TriggerResolution < ApplicationRecord
  belongs_to :activity
  belongs_to :product

  validates :category, presence: true
end

app/models/trigger_resolution_episode.rb
class TriggerResolutionEpisode < ApplicationRecord
  belongs_to :health_episode
  belongs_to :trigger_resolution
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

  has_many :prescriptions
  has_many :prescription_schedules, through: :prescriptions
  has_many :check_ins, through: :prescription_schedules


  validates :email, uniqueness: true, presence: true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_check_in, only: [:update]


  def update

    @check_in.update(status: 'complete')
    @check_in.update(completed_timestamp: DateTime.now())
    # redirect_to root_path
  end

  private

  def set_check_in
    @check_in = CheckIn.find(params[:id])
  end

end

app/controllers/inbound_sms_controller.rb
require 'nexmo'

class InboundSmsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    check_in = User.find_by(phone_number: params[:msisdn]).check_ins.where(status: 'incomplete').sort_by { |check_in| check_in.created_at}.first

    text_message = TextMessage.create(
      to: params[:to],
      from: params[:msisdn],
      text: params[:text],
      message_id: params[:messageId],
      is_inbound: true,
      check_in: check_in
      )

    if text_message.text == "1"
      check_in.update(status: 'complete')
    else
      check_in.update(status: 'missed')
    end
    reply(text_message)
    head :ok
  end

  private

  def reply(text_message)
    nexmo = Nexmo::Client.new(
      api_key: ENV["NEXMO_API_KEY"],
      api_secret: ENV["NEXMO_SECRET_KEY"]
    )

    nexmo.sms.send(
    from: text_message.to,
    to: text_message.from,
    text: 'We recieved your answer, thank you!'
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def schedule
  end
end

app/controllers/prescription_schedules_controller.rb
class PrescriptionSchedulesController < ApplicationController

  def create
    days_of_week = ""
    params.each do |param|
      if param[0].include? "day"
        days_of_week += param[0]
        days_of_week += ','
      end
    end
    if days_of_week[-1] == ','
      days_of_week.chop
    end
    as_needed = params[:as_needed] ? true : false
    prescription = Prescription.find(params[:prescription_id])
    if params[:hours].length == 1
      scheduled_time = "0#{params[:hours]}:#{params[:minutes]}"
    else
      scheduled_time = "#{params[:hours]}:#{params[:minutes]}"
    end
    prescription_schedule = PrescriptionSchedule.create(day_of_week: days_of_week, as_needed: as_needed, prescription: prescription, time_of_day: scheduled_time)

    redirect_to prescriptions_path
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:check_schedule]
  def index
    @prescriptions = Prescription.where(user: current_user)
  end
  def new
    @prescription = Prescription.new


    @all_products = Product.all.map do |product|
      product.name
    end
  end

  def create
    product = Product.find_by(name: params[:prescription][:product])
    amount = params[:prescription][:amount].to_f
    instructions = instructions = params[:prescription][:instructions]
    end_date = Date.new(params[:prescription]["end_date(1i)"].to_i, params[:prescription]["end_date(2i)"].to_i, params[:prescription]["end_date(3i)"].to_i )
    start_date = Date.new(params[:prescription]["start_date(1i)"].to_i, params[:prescription]["start_date(2i)"].to_i, params[:prescription]["start_date(3i)"].to_i )
    @prescription = Prescription.new(product: product, amount: amount, instructions: instructions, end_date: end_date, start_date: start_date)
    @prescription.user = current_user

    if @prescription.save
      redirect_to root_path
    else
      render :new
    end
  end

  def check_schedule
    @prescription_schedules = @prescription.prescription_schedules
    if @prescription_schedules
      respond_to do |format|
        format.js { render "show_schedules.js.erb", prescription: @prescription, schedules: @prescription_schedules}
      end
    else
      flash[:notice] = "No schedules for current prescription"
      render :index
    end
  end

  private

  def set_prescription
    @prescription = Prescription.find(params[:prescription_id])
  end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_action :authenticate_user!

  def index
    # @prescription_schedules_today = current_user.prescription_schedules.select do |schedule|
    #   schedule.day_of_week.split(",").include? Date.today.strftime("%A")
    # end

    @check_ins = current_user.check_ins.where(scheduled_date: Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/check_ins/update.js.erb
var current_check_in = document.querySelector("[data-id='<%= @check_in.id %>']");

current_check_in.innerText = 'yes';
current_check_in.nextSibling.nextSibling.style.display= 'none';

app/views/prescriptions/_form.html.erb
<%= simple_form_for(@prescription) do |f|%>

  <%= f.label :prodct, "Product Name" %>
  <%= f.input :product, collection: @all_products, label: false %>

  <%= f.label :amount, "Amount (in grams)" %>
  <%= f.input :amount, label: false %>

  <%= f.label :instructions, "Enter instructions" %>
  <%= f.input :instructions, label: false, as: :text %>

  <%= f.label :start_date, "Start date" %>
  <%= f.input :start_date %>

  <%= f.label :end_date, "End date" %>
  <%= f.input :end_date %>

  <%= f.button :submit, value: "Submit", class: "btn btn-primary mt-3" %>


<% end %>

app/views/prescriptions/_new_prescription_schedule_form.html.erb
<h4 class="text-center m-2">Add new</h1>
<%= form_with  url: prescription_prescription_schedules_url(@prescription), local: true do |f| %>
  <div class="row border mr-5 ml-5">
    <div class="col-sm-2 text-center p-3">
      <input type="number" min="0" max="23" name="hours" placeholder="23">:
      <input type="number" min="0" max="59" name="minutes" placeholder="00">
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Sunday" value="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Monday" value="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Tuesday" value="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Wednesday" value="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Thursday"value="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Friday"lue="1" class='mr-2'>
    </div>
    <div class="col-sm-1 text-center p-3">
      <input type="checkbox" class="hidden" name="Saturday" value="1" class='mr-2'>
    </div>
    <div class="col-sm-3 text-center p-3">
      <input type="checkbox" class="hidden" name="as_needed" value="1" class='mr-2'>
    </div>
  </div>
  <div class="text-center p-3">
    <%= submit_tag 'Save', class: "btn btn-secondary mt-2 m-auto" %>
  </div>
<% end %>

app/views/prescriptions/_prescription_schedules.html.erb
<div class="row mr-5 ml-5">
  <div class="col-sm-2 text-center m-auto p-3">
    <h4>Time</h4>
  </div>
  <div class="col-sm-7 text-center p-3">
    <h4>Days of week</h4>
  </div>
  <div class="col-sm-3 text-center p-3">
    <h4>As needed</h4>
  </div>
</div>
<div class="row mr-5 ml-5">
  <div class="col-sm-2 text-center p-2">
    <span></span>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Sun</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Mon</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Tue</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Wed</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Thur</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Fri</h6>
  </div>
  <div class="col-sm-1 text-center p-2">
    <h6>Sat</h6>
  </div>
  <div class="col-sm-3 text-center p-2">
    <span></span>
  </div>
</div>
<% @prescription_schedules.each do |schedule| %>
  <div class="row border border mr-5 ml-5">
    <div class="col-sm-2 border-right text-center p-3">
      <p><%= schedule.time_of_day %></p>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Sunday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Monday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Tuesday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Wednesday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Thursday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Friday") ? "x" : "" %>
    </div>
    <div class="col-sm-1 border-right text-center p-3">
      <%= schedule.day_of_week.split(",").include?("Saturday") ? "x" : "" %>
    </div>
    <div class="col-sm-3 border-right text-center p-3">
      <%= schedule.as_needed ? "x" : "" %>
    </div>
  </div>
<% end %>
<div class="bg-light">
  <%= render 'new_prescription_schedule_form' %>
</div>

app/views/prescriptions/index.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-5">
    My Prescriptions
  </h1>
  <div class="row">
    <div class="col-sm">
      <h3 class='mb-4'>Name</h3>
    </div>
    <div class="col-sm">
      <h3 class='mb-4'>Intructions</h3>

    </div>
    <div class="col-sm">
      <h3 class='mb-4'>Amount</h3>
    </div>
    <div class="col-sm">
      <h3 class='mb-4'>Start Date</h3>
    </div>
    <div class="col-sm">
      <h3 class='mb-4'>End Date</h3>
    </div>
    <div class="col-sm">
      <h3><span></span></h3>
    </div>
  </div>
  <% @prescriptions.each do |prescription| %>

  <div class="row border-bottom">
    <div class="col-sm p-2">
      <p><%= prescription.product.name %></p>
    </div>
    <div class="col-sm p-2">
      <p><%= prescription.instructions %></p>
    </div>
    <div class="col-sm p-2">
      <p><%= prescription.amount %> grams</p>
    </div>
    <div class="col-sm p-2">
      <p><%= prescription.start_date.strftime("%d of %B, %Y") %></p>
    </div>
    <div class="col-sm p-2">
      <p><%= prescription.end_date.strftime("%d of %B, %Y") %></p>
    </div>
    <div class="col-sm m-auto">
      <%= link_to prescription_check_schedule_path(prescription), remote: true  do%>
        <button class='btn-primary btn-sm'>Check Schedules</button>
      <% end %>
    </div>
  </div>
  <div class="schedule-form-js" id='schedule-form-<%= prescription.id %>'>
  </div>
  <% end %>
</div>

app/views/prescriptions/new.html.erb
<div class="container text-center m-4">
  <h1>New Prescription</h1>
  <%= render 'form' %>
</div>

app/views/prescriptions/show_schedules.js.erb
document.querySelectorAll('.schedule-form-js').forEach((schedule) =>
    {
      if (schedule.children){
        Array.from(schedule.children).forEach((child) => {
          child.classList = []
         child.innerHTML = ""
        });
      }
    }
  );
var current_schedule = document.getElementById("schedule-form-<%= j (@prescription.id) %>")

// current_schedule.style.display = "";
current_schedule.innerHTML += '<%= j (render partial: "prescription_schedules") %>'