config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "schedule#index"

  resources :check_ins, only: [:update]

  post 'inbound_sms', to: 'inbound_sms#create'

  resources :prescriptions, only: [:index, :new, :create] do
    resources :prescription_schedules, only: [:create]

    get 'check_schedule', to: "prescriptions#check_schedule"
  end


  # For being able to see sidekiq processes if you are an admin
  require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :trigger_resolutions
  has_many :trigger_resolution_episodes, through: :trigger_resolutions

  validates :name, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  after_create :set_sms_time

  belongs_to :prescription_schedule
  has_one :prescription, through: :prescription_schedule
  validates :scheduled_date, presence: true
  validates :scheduled_time, presence: true

  has_one :text_message

  private

  def set_sms_time
    SendSmsJob.set(wait_until: ("#{self.scheduled_date} #{self.scheduled_time}").to_datetime).perform_later(self.id)
  end
end

app/models/episode_symptom.rb
class EpisodeSymptom < ApplicationRecord
  belongs_to :symptom
  belongs_to :health_episode
end

app/models/health_episode.rb
class HealthEpisode < ApplicationRecord
  has_many :trigger_resolution_episodes
  has_many :episode_symptoms
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  after_create :set_defaults
  belongs_to :user
  belongs_to :product
  has_many :prescription_schedules
  has_many :check_ins, through: :prescription_schedules
  validates :product, presence: true
  validates :amount, presence:true
  validates :instructions, presence: true
  validates :end_date, presence: true
  validates :start_date, presence: true


  private

  def set_defaults
    self.update(active: true)
  end
end

app/models/prescription_schedule.rb
class PrescriptionSchedule < ApplicationRecord
  after_initialize :set_defaults
  belongs_to :prescription
  has_many :check_ins

  validates :prescription, presence: true
  validates :day_of_week, presence: true
  validates :time_of_day, presence: true

  def set_defaults
    self.update(as_needed: false) unless self.as_needed
    self.update(day_of_week: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday") unless self.day_of_week
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prescriptions
  has_many :trigger_resolutions
  has_many :trigger_resolution_episodes, through: :trigger_resolutions
end

app/models/sms.rb
class Sms < ApplicationRecord
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :episode_symptoms
  has_many :health_episodes, through: :episode_symptoms

  validates :name, uniqueness: true, presence: true
end

app/models/text_message.rb
class TextMessage < ApplicationRecord
  belongs_to :check_in

end

app/models/trigger_resolution.rb
class TriggerResolution < ApplicationRecord
  belongs_to :activity
  belongs_to :product

  validates :category, presence: true
end

app/models/trigger_resolution_episode.rb
class TriggerResolutionEpisode < ApplicationRecord
  belongs_to :health_episode
  belongs_to :trigger_resolution
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

  has_many :prescriptions
  has_many :prescription_schedules, through: :prescriptions
  has_many :check_ins, through: :prescription_schedules


  validates :email, uniqueness: true, presence: true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_check_in, only: [:update]


  def update

    @check_in.update(status: 'complete')
    @check_in.update(completed_timestamp: DateTime.now())
    # redirect_to root_path
  end

  private

  def set_check_in
    @check_in = CheckIn.find(params[:id])
  end

end

app/controllers/inbound_sms_controller.rb
require 'nexmo'

class InboundSmsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    check_in = User.find_by(phone_number: params[:msisdn]).check_ins.where(status: 'incomplete').sort_by { |check_in| check_in.created_at}.first

    text_message = TextMessage.create(
      to: params[:to],
      from: params[:msisdn],
      text: params[:text],
      message_id: params[:messageId],
      is_inbound: true,
      check_in: check_in
      )

    if text_message.text == "1"
      check_in.update(status: 'complete')
    else
      check_in.update(status: 'missed')
    end
    reply(text_message)
    head :ok
  end

  private

  def reply(text_message)
    nexmo = Nexmo::Client.new(
      api_key: ENV["NEXMO_API_KEY"],
      api_secret: ENV["NEXMO_SECRET_KEY"]
    )

    nexmo.sms.send(
    from: text_message.to,
    to: text_message.from,
    text: 'We recieved your answer, thank you!'
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def schedule
  end
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_action :authenticate_user!

  def index
    # @prescription_schedules_today = current_user.prescription_schedules.select do |schedule|
    #   schedule.day_of_week.split(",").include? Date.today.strftime("%A")
    # end

    @check_ins = current_user.check_ins.where(scheduled_date: Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/schedule.html.erb
<h1>Pages#schedule</h1>
<p>Find me in app/views/pages/schedule.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "My Prescriptions", prescriptions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Prescription", new_prescription_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/omergeva", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>